### ISSUE TITLE
Does this work with response json?

### ISSUE THREAD

**Issue by ChrisJBurns** [swagger-model-validator/swagger-model-validator#117]
I am trying to get this library to work but for some reason, it fails regardless, can you show how you are creating your Swagger client?

My use case, is during the unit tests, I want to run the function, get the json data back, and then validate it against the Open API 3 spec.

**Comment by brodyd** [comment]
This takes in the Swagger Definition and validates the body against the type defined in the definition.
It could be used for validating a response.  You'd need to supply the response definition and then call the validator with that and the body.

Here is a very simple example of a direct validation of a model.

    var data = {
            sample: true,
            location: {
                top: 1,
                left: 1,
                right: 5,
                bottom: 5
            }
        };

        var models = {
            dataModel: {
                required: [ "sample" ],
                properties: {
                    sample: {
                        type: "boolean"
                    },
                    location: {
                        $ref: "#/components/schemas/Location"
                    }
                }
            },
            Location: {
                required: [ "top", "left" ],
                properties: {
                    top: {
                        type: "integer"
                    },
                    left: {
                        type: "integer"
                    },
                    right: {
                        type: "integer"
                    },
                    bottom: {
                        type: "integer"
                    }
                }
            }
        };

        var errors = validator.validate(data, models["dataModel"], models);

        test.expect(1);
        test.ok(errors.valid);
        test.done();

We are essentially calling a subcomponent of the validator and forcing it to compare a data object with a specific model definition.  We are passing in a set of all models because we have a referenced model we need to access.  If there are no referenced models then that can be left out (I think).

**Comment by ChrisJBurns** [comment]
So the bit I'm having problems with is the use of the `swagger` client? In the `README.md` it says "Create a validator and pass your swagger client into it." But how is the swagger client initialised as I can't see a way to initialise if using the `swagger-client` library using OpenAPI 3.

**Comment by ChrisJBurns** [comment]
Ahhh I see! That's where the understanding was perhaps wrong. I understood that it was as simple as just using the Validator inside of a Jest test to confirm if the JSON Response back from certain functions match what the OA3 Specification describes. It turns out there a lot more integrating inside of the Server itself.

**Comment by brodyd** [comment]
I'll close this as answered.  Please reopen if you need more.
