### ISSUE TITLE
Usage in readme not clear enough 

### ISSUE THREAD

**Issue by ArinCantCode** [swagger-model-validator/swagger-model-validator#135]
I find the readme confusing as it doesn't give any real word example and does not explain what swagger client is.

Right now i'm not sure if swagger client is the library [swagger-client](https://www.npmjs.com/package/swagger-client)?

As for `var validation = swagger.validateModel("modelName", jsonObject, _allowBlankTarget_, _disallowExtraProperties_);` what is swagger? is it the generated json from yaml file or the swagger client?

Also: 
`var validation = validator.validate(object, swaggerModel, swaggerModels, allowBlankTarget, disallowExtraProperties);`

What is really `swaggerModel` ? is it let say the defined schema response in my generated swagger.json? is models just all components?

**Comment by brodyd** [comment]
Swagger-Model-Validator was originally designed to work against swagger-node-express.

Ir was designed to be injected into the swagger client created by swagger-node-express so that it could get access to the swagger models it requires to validate.  If the client is not available then the second use (using the validator directly) can be tried.

The swagger model referred to in that call is the model that you are trying to validate against and the swagger models is a set of all of the models contained in the swagger definition.

If you look at the tests you should be able to see some examples of the validator used that way.

**Comment by ArinCantCode** [comment]
This cleared things up a bit for me thanks

**Comment by molinab297-unisys** [comment]
I agree with @brodyd . The readme is extremely lacking. You shouldn't expect people to look at the tests to figure out how to do basic things with the library.
