### ISSUE TITLE
allOf check doesn't take the attribute "disallowExtraProperties"

### ISSUE THREAD

**Issue by xuanzhaopeng** [swagger-model-validator/swagger-model-validator#140]
https://github.com/swagger-model-validator/swagger-model-validator/blob/master/lib/modelValidator.js#L379

In the code above, allOf use 'false' as default for "disallowExtraProperties".

It should extend from global settings.

**Comment by xuanzhaopeng** [comment]
This is invalid

**Comment by caarmen** [comment]
> This is invalid

Could you elaborate please?

(Hello 2 years later :) )

**Comment by brodyd** [comment]
I think with allOf each object has to include all properties of all included types so extra properties must eb supported or it will fail in one type in the allOf has a properties another type in the allOf does not have.

**Comment by caarmen** [comment]
@brodyd that makes sense, thanks 😊

**Comment by caarmen** [comment]
Hello again from another 2 years later 😅 

Referring to the linked code above, it does this:
```javascript
            for(var x in allOfArray) {
                field.type = allOfArray[x].type;
                var errorResult = validateType(name, value, allOfArray[x], models, allowBlankTargets, false);
                if (errorResult && !errorResult.valid) {
                    for (var y in errorResult.errors) {
                        errors.push(errorResult.errors[y]);
                    }
                }
            }
```

I understand, looking at this code, that since we iterate over each definition inside the `allOf`, and we check the set of all fields against each definition, `disallowExtraProperties` would indeed cause a failure, as exlpained by @brodyd.

For example, say we have:
* a `User` definition with `first_name` and `last_name` attributes
* an `Order` definition with a `price` attribute
* A model containing `allOf` with `User` and `Order`
* A json response like this:
    ```
    {
      "first_name": "john",
      "last_name": "doe",
      "price": 42.0,
    }
    ```
If we validate this json content against the individual definitions `User` and `Order`, with `disallowExtraProperties`, indeed, the validation against `User` with this data will fail, as `price` is not defined inside `User`.


But, couldn't there be another way, instead of iterating over each `allOf` item individually? Perhaps merge them into a new local definition, and then check the set of fields against this merged definition?

For example, merge into a local definition with attributes `first_name`, `last_name`, and `price`, then validate the json against this.

**Comment by brodyd** [comment]
But that isn't a user or an order then.  It is something else.  The validator would be wrong if it said that was a user or an order.  I think you should look at if this makes your model easier to use and understand or harder.

Nice to hear back from you by the way 🙂

I would tend to say that disallowing extra properties is probably not what you want to use in this case, and that you should perhaps think about your model and what it is trying to achieve.

Regards

Brody

________________________________

**Comment by caarmen** [comment]
Re :) 

Indeed, the user and order example is a bit weird, and not something you'd see in real life (it's totally not the example I have on my project). If it existed:
* I'd have defined a model `UserOrder` with an allOf of `User` and `Order`
* I'd like to validate that this json is a valid `UserOrder`
* This could be done by constructing a temporary object, during validation, containing all the combined attributes of `User` and `Order`, and comparing the json against that.

Since this "user order" thing is a bit weird example, let's take an example inspired from the swagger doc of [allOf](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/#allOf) instead.

```yaml
components:
  schemas:
    Pet:
      properties:
        name:
          type: string
    Dog:
      allOf: # Combines the main `Pet` schema with `Dog`-specific properties 
        - $ref: '#/components/schemas/Pet'
        - type: object
          # all other properties specific to a `Dog`
          properties:
            bark:
              type: boolean
            breed:
              type: string
              enum: [Dingo, Husky, Retriever, Shepherd]
```

We have a model `Pet` with an attribute `name`, and a model `Dog`, containing the attributes of Pet plus some dog-specific attributes.

I can have this json for a `Dog`:
```json
{
  "name": "Fido",
  "bark": true,
  "breed": "Retriever",
}
```

To validate that this json is indeed a valid `Dog`, the validator could temporarily create a model with all the properties of all the `allOf` definitions. If it were represented in yaml, it might look like:
```yaml
TempModel:
  properties:
    name:
      type: string
    bark:
      type: boolean
    breed:
      type: string
      enum: [Dingo, Husky, Retriever, Shepherd]
```

Then it could compare the json against this `TempModel`.

**Comment by brodyd** [comment]
Doesn't allOf work but just not with the preventExtraProperties set.  Seems like that would do what you want except for allowing extra properties...

I do see your point though.
________________________________

**Comment by caarmen** [comment]
> Doesn't allOf work but just not with the preventExtraProperties set. Seems like that would do what you want except for allowing extra properties... 

Yep that's exactly it!  It would be cool to have the check for disallow extra properties, so that the following json would be invalid (`wingspan` isn't a dog attribute 😅 ):

```json
{
  "name": "Fido",
  "bark": true,
  "breed": "Retriever",
  "wingspan": 42,
}
```

**Comment by brodyd** [comment]
I've had a look and it looks insanely complex.  The basic Json Schema that swagger is based off also has this exact same problem with additionProperties: false (effectively the same as disallowExtraProperties) so the problems been around for a while.

I'll think on it but I am not sure the work would be worth it as a nice to have given the more adult Json Schema does do it either.

I'll let you know if I come up with a way to manage this - but don't be hopeful.

Regards

Brody
________________________________
